---
- name: Install vsftp nfs samba dns dhcp
  hosts: all
  remote_user: root
  # remote_user: user
  # become: yes
  # become_method: sudo

  roles:
    - vsftpd
    - nfs
    - samba
    - dhcp
    - dns
